import { WatterContractPayload } from '../watter-contract-payload';

export const watterContractsStub: WatterContractPayload[] = [
  {
    Planta: '',
    Classe: '',
    'Nome do Contrato': '',
    Fornecedor: '',
    Acesso: '',
    'Tipo de Consumidor': '',
    'Modelo de Faturamento': '',
    'Número Instalação': '',
    'Número Medidor': '',
    'Número Cliente': '',
    Modalidade: '',
    'Código de Ligação (RGI)': '',
    Hidrômetro: '',
    'Número Contrato': '',
    'Codificação da Companhia': '',
    'Identificador de Usuário': '',
    'ID Eletrônico': '',
    Setor: '',
    'Código da Rua': '',
    'Inscrição Cadastral do Imóvel': '',
    'Código de Consumidor': '',
    'Campo Extra 1': '',
    'Campo Extra 2': '',
    'Campo Extra 3': '',
    'Campo Extra 4': '',
    'Contrato Relação 1': '',
    'Contrato Relação 2': '',
    'Unidade Métrica': '',
    'Forma de Pagamento': '',
    'Tipo de Acesso a Distribuidora': '',
    'Campo Extra de Acesso 1': '',
    Senha: '',
    'Endereço de Instalação': '',
    'Vigência Inicial': '',
    'Vigência Final': '',
    Observação: '',
    End: {},
    Ativado: '',
    'Loja Nova': '',
    Histórico: '',
    contractName: '',
  },
];
