export class EnergyBillPayload {
  'Planta': string;
  'Conta do Mês': string;
  'Série da Nota Fiscal': string;
  'Nº Nota Fiscal': string;
  'Reservado ao Fisco': string;
  'Chave de Acesso': string;
  'Data de Vencimento': string;
  'Emissão': string;
  'Código de Barras': string;
  'Leitura Anterior': string;
  'Leitura Atual': string;
  'Uso Sist': object;
  'Consumo PT VD': string;
  'Consumo FP CAP VD': string;
  'Consumo FP IND VD': string;
  'Demanda PT (kW)': string;
  'Demanda FP CAP (kW)': string;
  'Demanda FP IND (kW)': string;
  'Energia R': object;
  'Energia TE': string;
  'Energia TE Custo': string;
  'Demanda Faturada (kW)': string;
  'Demanda Faturada Custo': string;
  'Demanda Faturada PT Custo': string;
  'Demanda Faturada FP Custo': string;
  'Demanda Ultrapassada (kW)': string;
  'Demanda Ultrapassada Custo': string;
  'Demanda Ultrapassada PT Custo': string; 
  'Demanda Ultrapassada FP Custo': string; 
  'Dif Fat TUSD CCEE Custo': string; 
  'Dif Fat ENC CCEE Custo': string; 
  'Consumo A PT (TUSD) Custo': string; 
  'Consumo A PT (TE) Custo': string; 
  'Consumo A FP (TUSD) Custo': string; 
  'Consumo A FP (TE) Custo': string; 
  'Consumo Ener': object; 
  'Custo Ener': object; 
  'Consumo Decreto PT TUSD': string; 
  'Custo Decreto PT TUSD': string; 
  'Consumo Decreto FP TUSD': string; 
  'Custo Decreto FP TUSD': string; 
  'Consumo Decreto PT TE': string; 
  'Custo Decreto PT TE': string; 
  'Consumo Decreto FP TE': string; 
  'Custo Decreto FP TE': string; 
  'Saldo Injetado': string; 
  'Regime ICMS ACL Custo 1': string; 
  'Regime ICMS ACL Custo 1A': string; 
  'Regime ICMS ACL Custo 2': string; 
  'Regime ICMS ACL Custo 2A': string; 
  'Regime PIS COFINS ACL Custo 1': string; 
  'Regime PIS COFINS ACL Custo 1A': string; 
  'Regime PIS COFINS ACL Custo 2': string; 
  'Regime PIS COFINS ACL Custo 2A': string; 
  'Benefício Tarifário Bruto': string; 
  'Benefício Tarifário Líquido': string; 
  'Demanda Lei Estadual Custo': string; 
  'Ufer TE PT Custo': string; 
  'Ufer FP TE Custo': string; 
  'ADD Bandeira AM Custo': string; 
  'ADD Bandeira VM Custo': string; 
  'ADD Bandeira Escassez': string; 
  'Encargo de Conexão Custo': string; 
  'PIS/PASEP Custo': string; 
  'Desconto PIS/PASEP': string; 
  'PIS/PASEP JUDICIAL': string; 
  'COFINS Custo': string; 
  'Desconto COFINS': string; 
  'COFINS JUDICIAL': string; 
  'C de Disp - REN': object; 
  'PC': object; 
  'desconto_Juros_de_Mora': string;
  'Desconto_At': object;
  'cobranças': string;
  'COSIP_CIP_Custo': string;
  'Cosip_CIP_REF_VCTO': string;
  'icms': string;
  'ICMS_Judicial': string;
  'taxa_Entrega_Outra_Localidade': string;
  'ressarc': object;
  'devolução_Fatura_1': string;
  'Devolução_Fatura_2': string;
  'devolução_Fatura_3': string;
  'Devolução_Fatura_4': string;
  'devolução_Liminar': string;
  'taxa_Religue': string;
  'Taxa_Desligue': string;
  'parcelamento': string;
  'multas_REF_VCTO': string;
  'juros_De_Mora_REF_VCTO': string;
  'atualização_Monetária_REF_VCTO': string;
  'Taxa_Revisão_De_Fatura': string;
  'taxa_Visita_Técnica': string;
  'taxa_De_Lixo': string;
  'taxa_TSV-Emissão_De_2°_Via': string;
  'tarifa_Energia_Reativa_PT_C/Imposto': string;
  'tarifa_Energia_Reativa_PT_S/Imposto': string;
  'Tarifa_Energia_Reativa_FP_C/Imposto': string;
  'Tarifa_Energia_Reativa_FP_S/Imposto': string;
  'Tarifa_Demanda_Faturada_C/Imposto': string;
  'Tarifa_Demanda_Faturada_S/Imposto': string;
  'tarifa_Demanda_LEI_C/Imposto': string;
  'Tarifa_Demanda_LEI_S/Imposto': string;
  'tarifa_Consumo_PT_C/Imposto': string;
  'Tarifa_Consumo_PT_S/Imposto': string;
  'tarifa_Consumo_FP_C/Imposto': string;
  'Tarifa_Consumo_FP_S/Imposto': string;
  'tarifa_Consumo_PT_TE_C/Imposto': string;
  'Tarifa_Consumo_PT_TE_S/Imposto': string;
  'tarifa_Consumo_FP_TE_C/Imposto': string;
  'Tarifa_Consumo_FP_TE_S/Imposto': string;
  'tarifa_Uso_Sist': object;
  'tarifa_Energia_TE_Custo_C/Imposto': string;
  'tarifa_Energia_TE_Custo_S/Imposto': string;
  'tarifa_Demanda_Faturada_PT_C/Imposto': string;
  'Tarifa_Demanda_Faturada_PT_S/Imposto': string;
  'Tarifa_Demanda_Ultrapassada_PT_C/Imposto': string;
  'tarifa_Demanda_Ultrapassada_PT_S/Imposto': string;
  'Tarifa_Demanda_Ultrapassada_FP_C/Imposto': string;
  'Tarifa_Demanda_Ultrapassada_FP_S/Imposto': string;
  'penal': object;
  'crédito_Na_Próxima_Fat.': string;
  'Devolução_De_Pag_Duplic.': string;
  'total': string;
  'nível_De_Informações_Da_Fatura': string;
  'observações': string;
  'dic': string;
  'DIC_Apurado': string;
  'DMIC': string;
  'DMIC_Apurado': string;
  'FIC': string;
  'FIC_Apurado': string;
  'DICRI': string;
  'DICRI_Apurado': string;
  'total_Compra_De_Energia': string;
  'descrição_Da_Nota': string;
  'fornecedor': string;
  'código_De_Identificação': string;
  'número_Instalação': string;
  'Número_Medidor': string;
  'Número_Cliente': string;
  'modalidade': string;
  'CódigoDeLigação(RGI)': string;
  'hidrômetro': string;
  'Número_Contrato': string;
  'código_De_Consumidor': string;
}
