export class EnergyBillPayload {
  'Planta': string;
  'Conta do Mês': string;
  'Série da Nota Fiscal': string;
  'Nº Nota Fiscal': string;
  'Reservado ao Fisco': string;
  'Chave de Acesso': string;
  'Data de Vencimento': string;
  'Emissão': string;
  'Código de Barras': string;
  'Leitura Anterior': string;
  'Leitura Atual': string;
  'Uso Sist': string;
  'Consumo PT VD': string;
  'Consumo FP CAP VD': string;
  'Consumo FP IND VD': string;
  'Demanda PT (kW)': string;
  'Demanda FP CAP (kW)': string;
  'Demanda FP IND (kW)': string;
  'Energia R': object;
  'Energia TE': string;
  'Energia TE Custo': string;
  'Demanda Faturada (kW)': string;
  'Demanda Faturada Custo': string;
  'Demanda Faturada PT Custo': string;
  'Demanda Faturada FP Custo': string;
  'Demanda Ultrapassada (kW)': string;
  'Demanda Ultrapassada Custo': string;
  'Demanda Ultrapassada PT Custo': string;
  'Demanda Ultrapassada FP Custo': string;
  'Dif Fat TUSD CCEE Custo': string;
  'Dif Fat ENC CCEE Custo': string;
  'Consumo A PT (TUSD) Custo': string;
  'Consumo A PT (TE) Custo': string;
  'Consumo A FP (TUSD) Custo': string;
  'Consumo A FP (TE) Custo': string;
  'Consumo Ener': string;
  'Custo Ener': string;
  'Consumo Decreto PT TUSD': string;
  'Custo Decreto PT TUSD': string;
  'Consumo Decreto FP TUSD': string;
  'Custo Decreto FP TUSD': string;
  'Consumo Decreto PT TE': string;
  'Custo Decreto PT TE': string;
  'Consumo Decreto FP TE': string;
  'Custo Decreto FP TE': string;
  'Saldo Injetado': string;
  'Regime ICMS ACL Custo 1': string;
  'Regime ICMS ACL Custo 1A': string;
  'Regime ICMS ACL Custo 2': string;
  'Regime ICMS ACL Custo 2A': string;
  'Regime PIS COFINS ACL Custo 1': string;
  'Regime PIS COFINS ACL Custo 1A': string;
  'Regime PIS COFINS ACL Custo 2': string;
  'Regime PIS COFINS ACL Custo 2A': string;
  'Benefício Tarifário Bruto': string;
  'Benefício Tarifário Líquido': string;
  'Demanda Lei Estadual Custo': string;
  'Ufer TE PT Custo': string;
  'Ufer FP TE Custo': string;
  'ADD Bandeira AM Custo': string;
  'ADD Bandeira VM Custo': string;
  'ADD Bandeira Escassez': string;
  'Encargo de Conexão Custo': string;
  'PIS/PASEP Custo': string;
  'Desconto PIS/PASEP': string;
  'PIS/PASEP JUDICIAL': string;
  'COFINS Custo': string;
  'Desconto COFINS': string;
  'COFINS JUDICIAL': string;
  'C de Disp - REN': object;
  'PC': object;
  'Desconto Juros de mora': string;
  'Desconto At': object;
  'Cobranças': string;
  'COSIP/CIP Custo': string;
  'COSIP/CIP REF VCTO': string;
  'ICMS': string;
  'ICMS JUDICIAL': string;
  'Taxa Entrega outra Localidade': string;
  'Ressarc': object;
  'Devolução Fatura 1': string;
  'Devolução Fatura 2': string;
  'Devolução Fatura 3': string;
  'Devolução Fatura 4': string;
  'Devolução Liminar': string;
  'Taxa Religue': string;
  'Taxa Desligue': string;
  'Parcelamento': string;
  'Multas REF VCTO': string;
  'Juros de Mora REF VCTO': string;
  'Atualização Monetária REF VCTO': string;
  'Taxa Revisão de Fatura': string;
  'Taxa Visita Técnica': string;
  'Taxa de Lixo': string;
  'Taxa TSV-Emissão de 2° Via': string;
  'Tarifa Energia Reativa PT C/ Imposto': string;
  'Tarifa Energia Reativa PT S/ Imposto': string;
  'Tarifa Energia Reativa FP C/ Imposto': string;
  'Tarifa Energia Reativa FP S/ Imposto': string;
  'Tarifa Demanda Faturada C/ Imposto': string;
  'Tarifa Demanda Faturada S/ Imposto': string;
  'Tarifa Demanda LEI C/ Imposto': string;
  'Tarifa Demanda LEI S/ Imposto': string;
  'Tarifa Consumo PT C/ Imposto': string;
  'Tarifa Consumo PT S/ Imposto': string;
  'Tarifa Consumo FP C/ Imposto': string;
  'Tarifa Consumo FP S/ Imposto': string;
  'Tarifa Consumo PT TE C/ Imposto': string;
  'Tarifa Consumo PT TE S/ Imposto': string;
  'Tarifa Consumo FP TE C/ Imposto': string;
  'Tarifa Consumo FP TE S/ Imposto': string;
  'Tarifa Uso Sist': string;
  'Tarifa Energia TE Custo C/ Imposto': string;
  'Tarifa Energia TE Custo S/ Imposto': string;
  'Tarifa Demanda Faturada PT C/ Imposto': string;
  'Tarifa Demanda Faturada PT S/ Imposto': string;
  'Tarifa Demanda Ultrapassada PT C/ Imposto': string;
  'Tarifa Demanda Ultrapassada PT S/ Imposto': string;
  'Tarifa Demanda Ultrapassada FP C/ Imposto': string;
  'Tarifa Demanda Ultrapassada FP S/ Imposto': string;
  'Penal': object;
  'Crédito na próxima Fat.': string;
  'Devolução de pag Duplic.': string;
  'Total': string;
  'Nível de Informações da Fatura': string;
  'Observações': string;
  'DIC': string;
  'DIC Apurado': string;
  'DMIC': string;
  'DMIC Apurado': string;
  'FIC': string;
  'FIC Apurado': string;
  'DICRI': string;
  'DICRI Apurado': string;
  'Total Compra de Energia': string;
  'Descrição da Nota': string;
  'Fornecedor': string;
  'Código de Identificação': string;
  'Número Instalação': string;
  'Número Medidor': string;
  'Número Cliente': string;
  'Modalidade': string;
  'Código de Ligação (RGI)': string;
  'Hidrômetro': string;
  'Número Contrato': string;
  'Código de Consumidor': string;
}