export class EnergyContract {
  'Planta': string;
  'Classe': string;
  'Nome do Contrato': string;
  'Fornecedor': string;
  'Horário de Ponta': string;
  'Código de Identificação': string;
  'Código Fiscal de Operação': string;
  'Roteiro de Leitura': string;
  'Tipo de Consumidor (Energia)': string;
  'Número Instalação': string;
  'Número Medidor': string;
  'Número Cliente': string;
  'Modalidade': string;
  'Demanda Ponta': string;
  'Demanda Fora Ponta': string;
  'Tensão Contratada (V)': string;
  'Acesso as Contas': string;
  'Código de Ligação (RGI)': string;
  'Hidrômetro': string;
  'Número Contrato': string;
  'Codificação da Companhia': string;
  'Identificador de Usuário': string;
  'ID Eletrônico': string;
  'Setor': string;
  'Código da Rua': string;
  'Inscrição Cadastral do Imóvel': string;
  'Código de Consumidor': string;
  'Campo Extra 2': string;
  'Campo Extra 3': string;
  'Campo Extra 4': string;
  'Unidade Métrica': string;
  'Forma de Pagamento': string;
  'Site de Acesso': string;
  'Tipo de Acesso a Distribuidora': string;
  'Campo Extra de Acesso 1': string;
  'Senha': string;
  'Endereço de Instalação': string;
  'Vigência Inicial': string;
  'Vigência Final': string;
  'Observação': string;
  'End': object;
  'Ativado': string;
  'Loja Nova': string;
}
