export class WatterBillPayload {
  'Planta': string;
  'Conta do Mês': string;
  'Série da Nota Fiscal': string;
  'Nº Nota Fiscal': string;
  'Vencimento': string;
  'Emissão': string;
  'Código de Barras': string;
  'Chave de Acesso': string;
  'Leitura Anterior': string;
  'Leitura Atual': string;
  'Consumo de Água m³': string;
  'Consumo de Esgoto m³': string;
  'Valor Água R$': string;
  'Valor Esgoto R$': string;
  'Total R$': string;
  'Nível de Informações da Fatura': string;
  'Observações': string;
  'Devolução Revisão Fatura': string;
  'Multa Esg': object;
  'Tx': object;
  'Multa Débitos R$': string;
  'Multa Créditos R$': string;
  'Multa Retenção R$': string;
  'Multa Acréscimo R$': string;
  'Parcelamento': string;
  'Taxa Serviços': string;
  'Tx de Coleta': string;
  'Tarifa Variável Água': string;
  'Tarifa Variável Esgoto': string;
  'Desconto Tarifário Esgoto': string;
  'Desconto Tarifário Água': string;
  'Tx de Lixo': string;
  'TX': object;
  'Multa REF VCTO': string;
  'Taxa Serviço Básico': string;
  'Juros de Mora REF VCTO': string;
  'Atualização Monetária REF VCTO': string;
  'Descrição da Nota': string;
  'Número Instalação': string;
  'Número Medidor': string;
  'Número Cliente': string;
  'Código de Ligação (RGI)': string;
  'Hidrômetro': string;
  'Número Contrato': string;
  'Identificador de Usuário': string;
  'Código de Consumidor': string;
}
