export class WatterContractPayload {
  'Planta': string;
  'Classe': string;
  'Nome do Contrato': string;
  'Fornecedor': string;
  'Acesso': string;
  'Tipo de Consumidor': string;
  'Modelo de Faturamento': string;
  'Número Instalação': string;
  'Número Medidor': string;
  'Número Cliente': string;
  'Modalidade': string;
  'Código de Ligação (RGI)': string;
  'Hidrômetro': string;
  'Número Contrato': string;
  'Codificação da Companhia': string;
  'Identificador de Usuário': string;
  'ID Eletrônico': string;
  'Setor': string;
  'Código da Rua': string;
  'Inscrição Cadastral do Imóvel': string;
  'Código de Consumidor': string;
  'Campo Extra 1': string;
  'Campo Extra 2': string;
  'Campo Extra 3': string;
  'Campo Extra 4': string;
  'Contrato Relação 1': string;
  'Contrato Relação 2': string;
  'Unidade Métrica': string;
  'Forma de Pagamento': string;
  'Tipo de Acesso a Distribuidora': string;
  'Campo Extra de Acesso 1': string;
  'Senha': string;
  'Endereço de Instalação': string;
  'Vigência Inicial': string;
  'Vigência Final': string;
  'Observação': string;
  'End': object;
  'Ativado': string;
  'Loja Nova': string;
  'Histórico': string;
  contractName: string;
}
